<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>images\desktop.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\active.png" />
    <None Remove="images\cty.png" />
    <None Remove="images\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\desktop.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFsharp" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\active.png" />
    <Resource Include="images\cty.png" />
    <Resource Include="images\logo.png" />
  </ItemGroup>

</Project>
